provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  redirect-test:
    lang: golang-middleware
    handler: ./redirect-test
    image: redirect-test:0.1
    labels:
      com.openfaas.scale.zero: false

